GET http://localhost:3000/users

###

POST http://localhost:3000/register
Content-Type: application/json

{
      "username": "GlennyBalls",
      "email": "fakemail22@gmail.com",
      "password": "Gamer22!",
      "age": 22,
      "termsAccepted": true
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "GlennyBalls",
  "password": "Gamer22!"
}
