GET http://localhost:3000/user/users

###

POST http://localhost:3000/user/register
Content-Type: application/json

{
      "username": "GlennyBalls",
      "email": "fakemail22@gmail.com",
      "password": "Gamer22!",
      "age": 22,
      "termsAccepted": true
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
  "username": "GlennyBalls",
  "password": "Gamer22!"
}

###
POST http://localhost:3000/user/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdsZW5ueUJhbGxzIiwiaWF0IjoxNjY1OTAwNDMzfQ.2Brhi5RL1ioCH3OJEMOEQnby6FgZJWjsjVrZPBXjDvI"
}

###
DELETE http://localhost:3000/user/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdsZW5ueUJhbGxzIiwiaWF0IjoxNjY1OTAwNDMzfQ.2Brhi5RL1ioCH3OJEMOEQnby6FgZJWjsjVrZPBXjDvI"
}
###
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkdsZW5ueUJhbGxzIiwiaWF0IjoxNjY1OTAxMDgwLCJleHAiOjE2NjU5MDEwOTV9.KMQFSf4x40-B-uNhnXEK4ko04GB_zw6ADdF7sNee9YQ
